apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: users-service-api
  description: Mock AWS Lambda CRUD API for managing users (Infomedia POC)
  tags:
    - lambda
    - rest
    - users
spec:
  type: openapi
  lifecycle: experimental
  owner: team-infomedia
  definition:
    $text: https://raw.githubusercontent.com/edfajardoCiandt/ifm-services/main/users-api/openapi.yaml
