apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vehicles-service
  description: AWS Lambda mock service for managing vehicles (Infomedia POC)
  annotations:
    backstage.io/techdocs-ref: dir:../vehicles-api
  tags:
    - lambda
    - service
    - vehicles
spec:
  type: service
  lifecycle: experimental
  owner: team-infomedia
  providesApis:
    - vehicles-service-api
